-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 14:56:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cloudy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cloudy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cloudy` DEFAULT CHARACTER SET utf8 ;
USE `cloudy` ;

-- -----------------------------------------------------
-- Table `cloudy`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloudy`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudy`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloudy`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `pasword` VARCHAR(255) NOT NULL,
  `profile_picture` VARCHAR(255) NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role_idx` (`Role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_id`)
    REFERENCES `cloudy`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudy`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloudy`.`Theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudy`.`Picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloudy`.`Picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `path` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Theme_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Picture_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Picture_Theme1_idx` (`Theme_id` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `cloudy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Picture_Theme1`
    FOREIGN KEY (`Theme_id`)
    REFERENCES `cloudy`.`Theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudy`.`Favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cloudy`.`Favorite` (
  `Picture_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Picture_id`, `User_id`),
  INDEX `fk_Picture_has_User_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Picture_has_User_Picture1_idx` (`Picture_id` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_has_User_Picture1`
    FOREIGN KEY (`Picture_id`)
    REFERENCES `cloudy`.`Picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Picture_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `cloudy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
